export const States = [
  { id: 'no', name: 'Seleccione un Estado...' },
  { id: 'Aguascalientes', name: 'Aguascalientes' },
  { id: 'Baja California', name: 'Baja California' },
  { id: 'Baja California Sur', name: 'Baja California Sur' },
  { id: 'Campeche', name: 'Campeche' },
  { id: 'Chiapas', name: 'Chiapas' },
  { id: 'Chihuahua', name: 'Chihuahua' },
  { id: 'CDMX', name: 'Ciudad de México' },
  { id: 'Coahuila', name: 'Coahuila' },
  { id: 'Colima', name: 'Colima' },
  { id: 'Durango', name: 'Durango' },
  { id: 'Estado de México', name: 'Estado de México' },
  { id: 'Guanajuato', name: 'Guanajuato' },
  { id: 'Guerrero', name: 'Guerrero' },
  { id: 'Hidalgo', name: 'Hidalgo' },
  { id: 'Jalisco', name: 'Jalisco' },
  { id: 'Michoacán', name: 'Michoacán' },
  { id: 'Morelos', name: 'Morelos' },
  { id: 'Nayarit', name: 'Nayarit' },
  { id: 'Nuevo León', name: 'Nuevo León' },
  { id: 'Oaxaca', name: 'Oaxaca' },
  { id: 'Puebla', name: 'Puebla' },
  { id: 'Querétaro', name: 'Querétaro' },
  { id: 'Quintana Roo', name: 'Quintana Roo' },
  { id: 'San Luis Potosí', name: 'San Luis Potosí' },
  { id: 'Sinaloa', name: 'Sinaloa' },
  { id: 'Sonora', name: 'Sonora' },
  { id: 'Tabasco', name: 'Tabasco' },
  { id: 'Tamaulipas', name: 'Tamaulipas' },
  { id: 'Tlaxcala', name: 'Tlaxcala' },
  { id: 'Veracruz', name: 'Veracruz' },
  { id: 'Yucatán', name: 'Yucatán' },
  { id: 'Zacatecas', name: 'Zacatecas' },
];
